// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnoAwxw7pbZCUd4XoyF9-WigZY3Dj2Dis',
    appId: '1:601402959408:android:9846207963d2c5f81ceff5',
    messagingSenderId: '601402959408',
    projectId: 'marinas-advmblprog',
    storageBucket: 'marinas-advmblprog.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxHzLek7Sg4J_aSGRkEqFveB_knEU7Pog',
    appId: '1:601402959408:web:dee5f740b7a4afcf1ceff5',
    messagingSenderId: '601402959408',
    projectId: 'marinas-advmblprog',
    authDomain: 'marinas-advmblprog.firebaseapp.com',
    storageBucket: 'marinas-advmblprog.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxHzLek7Sg4J_aSGRkEqFveB_knEU7Pog',
    appId: '1:601402959408:web:e3c57a1290202bc11ceff5',
    messagingSenderId: '601402959408',
    projectId: 'marinas-advmblprog',
    authDomain: 'marinas-advmblprog.firebaseapp.com',
    storageBucket: 'marinas-advmblprog.firebasestorage.app',
  );
}
